export enum Permissions {
  USERS = 'USERS',
  EMPLOYEES = 'EMPLOYEES',
  COMPANY_PROFILE = 'COMPANY_PROFILE',
  PREFERENCE_FILTER = 'PREFERENCE_FILTER',
  HEADS_OF_DEPARTMENTS = 'HEADS_OF_DEPARTMENTS',
  STATISTICS = 'STATISTICS',
  ORDERS = 'ORDERS',
}
